import Link from "next/link";

import { FaShoppingCart } from "react-icons/fa";

const Header = () => {
  return (
    <div className="w-[100vw] h-[120px] border-b-2">
      {/* Header Messages */}
      <div className="w-full h-[30%] flex justify-center items-center bg-[var(--border-color)]">
        <h1 className="text-[var(--main-color)]">
          All Products are generated by ChatGPT!
        </h1>
      </div>
      <div className="flex h-[70%] w-full justify-between items-center px-[5vw]">
        <Link
          href="/"
          className="text-[var(--border-color)] text-[2vw] font-Raleway"
        >
          VIDA GLOW
        </Link>
        <div className="w-[50%] flex justify-evenly">
          <p>JOURNAL</p>
          <p>FEEDBACK</p>
          <p>ABOUT US</p>
        </div>
        <div>
          <FaShoppingCart className="text-[2vw]" />
        </div>
      </div>
    </div>
  );
};

export default Header;
